server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Gateway-service
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: products
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: cart
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/cart/**
        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
